import raw from "../app/data/site-data.json";

/* The single import through which every figure on the page flows. The JSON is
   generated by `rw-ingest export-site-data` from the loaded dataset, plus a
   provenance-tracked block of cited World Bank / UN constants — components
   carry no data literals. Regenerate after every re-ingest. */

export interface Corridor {
  from_iso3: string;
  to_iso3: string;
  from_name: string;
  to_name: string;
  quotes: number;
  avg_cost_pct: number;
  from_ll?: number[];
  to_ll?: number[];
}

export interface SiteData {
  meta: {
    generated_utc: string;
    generator: string;
    source: { workbook: string; license: string; url: string };
  };
  pipeline: {
    quotes: number;
    quarters: number;
    first_quarter: string;
    last_quarter: string;
    corridors: number;
    providers: number;
    countries: number;
  };
  cited: {
    global_avg_cost_pct: number;
    global_avg_label: string;
    global_avg_url: string;
    sdg_target_pct: number;
    sdg_label: string;
    sdg_url: string;
    digital_avg_pct: number;
    cash_avg_pct: number;
    avg_split_label: string;
    avg_split_url: string;
    flows_usd_bn: number;
    flows_year: number;
    flows_label: string;
    flows_url: string;
  };
  computed: {
    quarter: string;
    amount_usd: number;
    quotes_total: number;
    transparent_quotes: number;
    non_transparent_quotes: number;
    avg_total_cost_pct: number;
    median_total_cost_pct: number;
    p90_total_cost_pct: number;
    digital_avg_pct: number | null;
    cash_avg_pct: number | null;
    digital_quotes: number;
    cash_quotes: number;
    cost_bands: { up_to_pct: number | null; quotes: number }[];
  };
  anatomy: {
    from_iso3: string;
    to_iso3: string;
    from_name: string;
    to_name: string;
    provider: string;
    instrument: string;
    currency: string;
    amount_usd: number;
    lcu_amount: number;
    total_cost_pct: number;
    fee_pct: number;
    margin_pct: number;
    arrives_pct: number;
    quarter: string;
  } | null;
  top_corridors: Corridor[];
  featured_corridors: Corridor[];
  roadmap: { id: string; desc: string; state: string; href: string }[];
}

export const SITE = raw as SiteData;

export const fmtInt = (n: number): string => n.toLocaleString("en-US");

export const fmtPct = (v: number): string => `${v.toFixed(2)}%`;
